# .github/workflows/publish.yml
name: Generate a build and push to another branch

on:
  push:
    branches:
      - Main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.1
          channel: stable
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --release
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: website
          FOLDER: build/web/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
